# Generated by Django 2.2 on 2019-05-27 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom_apply',
            fields=[
                ('classroom_apply_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('applicant_id', models.CharField(max_length=10)),
                ('classroom_id', models.CharField(max_length=20, null=True)),
                ('apply_date', models.DateField()),
                ('apply_section', models.IntegerField()),
                ('apply_reason', models.TextField()),
                ('apply_type', models.IntegerField()),
                ('edu_admin_id', models.CharField(max_length=10, null=True)),
                ('head_id', models.CharField(max_length=10, null=True)),
                ('apply_status', models.IntegerField(default=3)),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'classroom_apply',
                'ordering': ['apply_time'],
            },
        ),
        migrations.CreateModel(
            name='classroom_apply_finished',
            fields=[
                ('classroom_apply_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('applicant_id', models.CharField(max_length=10)),
                ('classroom_id', models.CharField(max_length=20, null=True)),
                ('apply_date', models.DateField()),
                ('apply_section', models.IntegerField()),
                ('apply_reason', models.TextField()),
                ('apply_type', models.IntegerField()),
                ('edu_admin_id', models.CharField(max_length=10, null=True)),
                ('head_id', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'classroom_apply_finished',
                'ordering': ['apply_date'],
            },
        ),
        migrations.CreateModel(
            name='classroom_equipment_status',
            fields=[
                ('classroom_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('classroom_size', models.IntegerField()),
                ('equipment_type', models.IntegerField()),
            ],
            options={
                'db_table': 'classroom_equipment_status',
            },
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('section', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'timetable',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='course_classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=20)),
                ('use_date', models.DateField()),
                ('use_section', models.IntegerField()),
            ],
            options={
                'db_table': 'course_classroom',
                'unique_together': {('classroom_id', 'use_date', 'use_section')},
            },
        ),
        migrations.CreateModel(
            name='classroom_use_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=20)),
                ('use_date', models.DateField()),
                ('use_section', models.IntegerField()),
            ],
            options={
                'db_table': 'classroom_use_record',
                'unique_together': {('classroom_id', 'use_date', 'use_section')},
            },
        ),
    ]
