# Generated by Django 2.2 on 2019-05-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('send_type', models.CharField(max_length=50)),
                ('send_time', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'EmailVerifyRecord',
            },
        ),
    ]
